version: '3'

services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend/src:/app/src
    environment:
      - PORT=5000
    ports:
      - "5000:5000"
  backend:
    build: ./backend
    volumes:
      - ./backend/src:/app/src
    ports:
      - "3000:3000"
  database:
    image: mongo
